BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '7'
            multiline: False
        Button:
            text: 'Square'
            on_press: app.handle_calculate(input_number.text)
        Label:
            id: output_label
            color: (1, 0.7, 0.8, 1)

    Label:
        id: label
        test: 'Enter a number and press "Square"'



